### ISSUE TITLE
Enable PAX Exam in parent POM

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-scripts#58]
Integration tests based on PAX Exam require the declaration of dependencies in the POM. We don't want to have every script directly depend on a specific framework version, so this has to be somehow configured commonly in the parent POM.

**Comment by bertfrees** [comment]
This was done in 10d081f6a5ec7debc6d0aeb01c0e55960a390ae2.

Later the declarations of the dependencies were moved to the modules-test-helper project to further simplify things (see https://github.com/daisy/pipeline-build-utils/pull/33 and https://github.com/daisy/pipeline-scripts/pull/99/files).
