### ISSUE TITLE
daisy202-to-epub3: epub:textref in SMIL refers to .html files instead of .xhtml files

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-scripts#76]
For instance:

``` xml
<seq xmlns:epub="http://www.idpf.org/2007/ops" id="mo1_seq23" epub:textref="content.html#dtb22">
```

The `epub:textref` in this example should've had the value `content.xhtml#dtb22`; there needs to be a regex adding the "x" here.

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-scripts/pull/104
