### ISSUE TITLE
daisy202-validator: fails to validate if the mime-type is x-wav

### ISSUE THREAD

**Issue by egli** [daisy/pipeline-scripts#81]
According to http://filext.com/file-extension/WAV a wav file can have the following mime-types: 
- `audio/wav`
- `audio/x-wav`
- `audio/wave`
- `audio/x-pn-wav`

Currently only `audio/wav` is supported. I think at least `audio/x-wav` should also be supported

**Comment by josteinaj** [comment]
Do you have production tools that use `audio/x-wav` ?

Should we suggest that users use `audio/wav` by displaying warnings for the three other variations?

**Comment by rdeltour** [comment]
Good catch, strictly speaking the spec doesn't mandate any particular media type.

@josteinaj, why would you issue warning for other media types ? For one thing, DAISY 3 mandates `audio/x-wav`

**Comment by josteinaj** [comment]
I just thought maybe `audio/wav` was recommended.

Let's allow them all with no warnings then?

**Comment by rdeltour** [comment]
> Let's allow them all with no warnings then?

yes, that sounds right to me (although I've never encountered the `audio/x-pn-wav` form...)

**Comment by egli** [comment]
cool, thanks

**Comment by bertfrees** [comment]
Fixed, see https://github.com/daisy/pipeline/issues/653.
