### ISSUE TITLE
html-to-epub3 is broken

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-scripts#93]
since html-to-fileset.xsl was moved to fileset-utils (https://github.com/daisy/pipeline-modules-common/commit/295455937134bd2856eada7f52d5aa39deb2974e).

We didn't notice this because there are no unit tests, so add some.

**Comment by bertfrees** [comment]
Slightly related: https://github.com/daisy/pipeline-modules-common/commit/ec907b40cc5ef90cad4e61fc8a2ba29e41d9c37c

**Comment by bertfrees** [comment]
@rdeltour Regarding https://github.com/daisy/pipeline-modules-common/commit/ec907b40cc5ef90cad4e61fc8a2ba29e41d9c37c: do you remember which scripts were broken? If not I think we should first add basic integration tests to all script before reverting your commit, and then see which ones break.

**Comment by rdeltour** [comment]
> Regarding daisy/pipeline-modules-common@ec907b4: do you remember which scripts were broken?

I don't remember specifically, but if I'm not mistaken the name of the new zip steps were changed, so it should be easy to find out by doing a search on the step name.

**Comment by bertfrees** [comment]
See PR: https://github.com/daisy/pipeline-scripts/compare/bugfix-93
